CREATE TABLE jobs (
    id uuid PRIMARY KEY,
    project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 200),
    cancel_requested_at timestamptz,
    idempotency_key text,
    creation_request_hash bytea,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CHECK ((idempotency_key IS NULL) = (creation_request_hash IS NULL)),
    CHECK (creation_request_hash IS NULL OR octet_length(creation_request_hash) = 32)
);

CREATE TABLE tasks (
    id uuid PRIMARY KEY,
    project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    job_id uuid REFERENCES jobs(id) ON DELETE CASCADE,
    task_type text NOT NULL CHECK (char_length(task_type) BETWEEN 1 AND 100),
    payload jsonb NOT NULL,
    payload_hash bytea NOT NULL CHECK (octet_length(payload_hash) = 32),
    status text NOT NULL CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELED')),
    priority integer NOT NULL DEFAULT 0,
    available_at timestamptz NOT NULL,
    execution_timeout interval NOT NULL CHECK (execution_timeout > interval '0'),
    overall_deadline timestamptz,
    max_attempts integer NOT NULL CHECK (max_attempts > 0),
    attempt_no integer NOT NULL DEFAULT 0 CHECK (attempt_no >= 0),
    lease_owner_instance_id uuid,
    lease_expires_at timestamptz,
    cancel_requested_at timestamptz,
    idempotency_key text,
    creation_request_hash bytea,
    result jsonb,
    result_hash bytea,
    final_error_type text,
    final_error_message text,
    completed_by_worker_instance_id uuid,
    completed_attempt_no integer,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    completed_at timestamptz,
    CHECK ((idempotency_key IS NULL) = (creation_request_hash IS NULL)),
    CHECK (creation_request_hash IS NULL OR octet_length(creation_request_hash) = 32),
    CHECK (result_hash IS NULL OR octet_length(result_hash) = 32),
    CHECK ((lease_owner_instance_id IS NULL) = (lease_expires_at IS NULL)),
    CHECK ((status = 'RUNNING') = (lease_owner_instance_id IS NOT NULL AND lease_expires_at IS NOT NULL)),
    CHECK ((status IN ('SUCCEEDED', 'FAILED', 'CANCELED')) = (completed_at IS NOT NULL)),
    CHECK (completed_attempt_no IS NULL OR completed_attempt_no > 0),
    UNIQUE (project_id, idempotency_key)
);

CREATE TABLE task_attempts (
    task_id uuid NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    attempt_no integer NOT NULL CHECK (attempt_no > 0),
    worker_name text NOT NULL,
    worker_instance_id uuid NOT NULL,
    started_at timestamptz NOT NULL,
    finished_at timestamptz,
    outcome text CHECK (outcome IS NULL OR outcome IN ('SUCCEEDED', 'RETRYABLE_FAILURE', 'PERMANENT_FAILURE', 'TIMEOUT', 'CANCELED')),
    error_type text,
    error_message text,
    execution_duration_ms bigint CHECK (execution_duration_ms IS NULL OR execution_duration_ms >= 0),
    lease_expired boolean NOT NULL DEFAULT false,
    result_hash bytea CHECK (result_hash IS NULL OR octet_length(result_hash) = 32),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (task_id, attempt_no)
);
